### ISSUE TITLE
Script to add "assumed redshift" columns to a LAT catalog

### ISSUE THREAD

**Issue by TarekHC** [davidsanchez/CTAtools#1]
Hi @davidsanchez ,

Do you think this repository would be a good place to upload the script (and generated catalog) that I sent around? I could document the script a bit, and upload it maybe to the "Catalogs" folder.

If you think this is not a good place, then I will upload it anywhere else, no worries.

Cheers!

Tarek

**Comment by davidsanchez** [comment]
thanks a lot.
david
