### ISSUE TITLE
Minimum energy

### ISSUE THREAD

**Issue by barbarabias** [davidsanchez/CTAtools#20]
The minimum energy needs to be set for each source. The first energy bin should fulfill the following conditions: (i) ts>2, (ii) excess>10, (iii) excess/bg<0.05).

**Comment by barbarabias** [comment]
Erratum: (iii) excess/bg>0.05)

**Comment by davidsanchez** [comment]
I try to fix that. coud you check?

**Comment by barbarabias** [comment]
Solved.
