### ISSUE TITLE
Fit energy range (when conditions are not satisfied).

### ISSUE THREAD

**Issue by barbarabias** [davidsanchez/CTAtools#29]
In cases when none of the bins satisfies the conditions (excess>10, TS>2, excess/bg<0.05) the analysis is performed in the whole energy range [50 GeV - 50 TeV]. It should be performed just in the first 2 bins.

**Comment by davidsanchez** [comment]
done need check

**Comment by barbarabias** [comment]
Problem: the maximum energy is set to the upper energy of the 3rd bin even if there are other bins that satisfy the requirements. Example (1FHLJ2150.2-1413, analysis for tau>1):

Excess  Sigma               Excess/Off   E_min[TeV]           E_max[TeV]    
1040.0    25.974804647      1.15173    0.409297481642   0.661808233192
456.404  17.2344482009    1.15664    0.661808233192   1.07010220479
152.203  8.56459092778    0.77735    1.07010220479     1.73028782549
71.6649  6.11220402876    0.859961  1.73028782549     2.79776636814
18.6919  2.53660475047    0.514815   2.79776636814    4.52381189729
-7.76619 -1.76608565089  -0.41384    4.52381189729    7.31471873961
-2.01114 -0.67124549264  -0.251043  7.31471873961    11.827439216
-1.49907 -0.68148084607  -0.333196  11.827439216      19.1242238269

Found minimal energy for the analysis to be 0.409297481642
Found maximal energy for the analysis to be 1.73028782549

**Comment by barbarabias** [comment]
Change of strategy: in cases when none of the bins satisfies the conditions (excess>10, TS>2, excess/bg<0.05) the analysis can be skipped.

**Comment by barbarabias** [comment]
Change of strategy: in cases when none of the bins satisfies the conditions (excess>10, TS>2, excess/bg<0.05) the analysis can be skipped.

**Comment by barbarabias** [comment]
When none of the bin satisfies the required conditions, the analysis is performed in the whole analysis range.
