### ISSUE TITLE
Need help downloading

### ISSUE THREAD

**Issue by atreachar** [davidsanchez/CTAtools#30]
Hi cold you help me download Ctatools. 
tried python install_CTAtools.py but didn't work. Got:

Cloning ebltable repo
fatal: destination path 'ebltable' already exists and is not an empty directory.
 Test the setup
*** COMMAND LINE TOOLS ***
python.............. /home/administrator/miniconda/bin/python
ipython............. /home/administrator/miniconda/bin/ipython
ctlike.............. /home/administrator/miniconda/bin/ctlike
*** PYTHON PACKAGES ***
ebltable............ MISSING
pyfits.............. /home/administrator/miniconda/lib/python2.7/site-packages/pyfits/__init__.pyc
astropy............. /home/administrator/miniconda/lib/python2.7/site-packages/astropy/__init__.pyc
yaml................ /home/administrator/miniconda/lib/python2.7/site-packages/yaml/__init__.pyc
iminuit............. MISSING
numpy............... /home/administrator/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc
scipy............... /home/administrator/miniconda/lib/python2.7/site-packages/scipy/__init__.pyc
matplotlib.......... /home/administrator/miniconda/lib/python2.7/site-packages/matplotlib/__init__.pyc
ebl................. MISSING
*** DIRECTORIES ***
FERMI_CATALOG_DIR... NO........ 
INST_DIR............ NO........ 
CONFIG_DIR.......... NO........

**Comment by barbarabias** [comment]
Solved. I suggested to delete old folders, download again the CTAtools, and run the installation command with "sudo".
