### ISSUE TITLE
csphagen does not create on off file when using a single observation?

### ISSUE THREAD

**Issue by barbarabias** [davidsanchez/CTAtools#34]
csphagen does not create on off file when using a single observation?
Impossible to run the analysis with a single simulated observation.
Error:
[CTA_ctools_script]: csphagen successfully ran
Traceback (most recent call last):
  File "Fit_DC1_Spectra.py", line 52, in <module>
    Ondata = pyfits.open(Onfile)[1].data
  File "/usr/lib/python2.7/dist-packages/pyfits/hdu/hdulist.py", line 124, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyfits/hdu/hdulist.py", line 266, in fromfile
    save_backup=save_backup, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyfits/hdu/hdulist.py", line 786, in _readfrom
    ffo = _File(fileobj, mode=mode, memmap=memmap)
  File "/usr/lib/python2.7/dist-packages/pyfits/file.py", line 132, in __init__
    self._open_filename(fileobj, mode, clobber)
  File "/usr/lib/python2.7/dist-packages/pyfits/file.py", line 487, in _open_filename
    self._file = fileobj_open(self.name, PYFITS_MODES[mode])
  File "/usr/lib/python2.7/dist-packages/pyfits/util.py", line 754, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: '/home/biasuzzi/Desktop/DC1_Analysis/EBL_10h_piv300GeV/PKS0507+17/PKS0507+17_onoff_stacked_pha_on.fits'

Apparently csphagen terminates succesfully (see log file).
[PKS0507+17_sim_csphagen.log](https://github.com/davidsanchez/CTAtools/files/2558462/PKS0507%2B17_sim_csphagen.log)

The whole analysis is in the compressed file at this link:
https://www.dropbox.com/s/dyg7n513xo1fxia/EBL_10h_piv300GeV.tar.gz?dl=0

To test the analysis run Fit_DC1_Spectra.py

**Comment by barbarabias** [comment]
In this case, csphagen cannot run with the option bkgmethod=REFLECTED because the observation points directly the source. It must be run with the option bkgmethod=CUSTOM, and either a ds9 region file or FITS WCS maps must be provided to specify the region where the background will be estimated.

**Comment by davidsanchez** [comment]
this seems to be a problem with ctools right?

**Comment by barbarabias** [comment]
To avoid this problem is sufficient to simulate the source with an offset (usually 0.4 deg). This is done in the csobssim, where ra=ra_source + 0.4 and dec=dec_source + 0.4.

**Comment by davidsanchez** [comment]
make sens.

**Comment by davidsanchez** [comment]
in the script, can you add a check that we have a=ra_source + 0.4 and dec=dec_source + 0.4. ?

**Comment by barbarabias** [comment]
Yes, I can add the offset, starting from the source coordinate. Is that you mean?

**Comment by davidsanchez** [comment]
I was thinking to a "if () " in the script that run csphagen. If this is not possible, then add a offset from the source position is a good workaround

**Comment by barbarabias** [comment]
Ok, I understood. THe problem is that if the source coordinates coincide with the pointing direction, we cannot use the bkgmethod=REFLECTED in csphagen. In that case we should use bkgmethod=CUSTOM, but it requires an additional file where the region for the bkg estimation is specified. I do not know how to produce such a file.

**Comment by barbarabias** [comment]
Add offset from the source position in Simulation/simulation.py (in csobssim part). The offset should be eventually be passed as an external parameter.
